/* ABI v1 — generated by perf-core/native-abi.
 * Do not edit by hand; regenerate from the Rust descriptors.
 */
#ifndef TQ_ABI_V1_H
#define TQ_ABI_V1_H
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Version ---- */
#define TQ_ABI_VERSION_MAJOR 1
#define TQ_ABI_VERSION_MINOR 0

typedef struct tq_abi_version {
    uint16_t major;
    uint16_t minor;
} tq_abi_version;

/* ---- Status codes (stable integer values) ---- */
typedef enum tq_abi_status {
    TQ_ABI_OK                  = 0,
    TQ_ABI_ERR_NULL_ARG        = 1,
    TQ_ABI_ERR_INVALID_BITS    = 2,
    TQ_ABI_ERR_INVALID_GROUPSZ = 3,
    TQ_ABI_ERR_NONFINITE_INPUT = 4,
    TQ_ABI_ERR_OVERFLOW        = 5,
    TQ_ABI_ERR_ALLOCATION      = 6,
    TQ_ABI_ERR_VERSION_MISMATCH = 7,
    TQ_ABI_ERR_BACKEND         = 8
} tq_abi_status;

/* ---- Encode request ---- */
typedef struct tq_abi_encode_request {
    tq_abi_version abi;
    const float*    data_ptr;
    size_t          n;
    uint8_t         bits;
    size_t          group_size;
    size_t**        out_shape;
    size_t          out_shape_capacity;
    uint8_t**       out_packed;
    size_t          out_packed_capacity;
    float**         out_scales;
    size_t          out_scales_capacity;
    float**         out_zeros;
    size_t          out_zeros_capacity;
} tq_abi_encode_request;

/* ---- Decode request ---- */
typedef struct tq_abi_decode_request {
    tq_abi_version abi;
    const uint8_t* packed_ptr;
    size_t         packed_len;
    const float*   scales_ptr;
    const float*   zeros_ptr;
    size_t         n;
    size_t         group_size;
    uint8_t        bits;
    float*         out_ptr;
} tq_abi_decode_request;

/* ---- Encode result ---- */
typedef struct tq_abi_encode_result {
    int32_t status;
    size_t  written_packed_len;
    size_t  written_shape_len;
    size_t  written_scales_len;
    size_t  written_zeros_len;
} tq_abi_encode_result;

/* ---- Release kinds (matching release per allocation owner) ---- */
typedef enum tq_abi_release_kind {
    TQ_ABI_RELEASE_SHAPE   = 0,
    TQ_ABI_RELEASE_PACKED  = 1,
    TQ_ABI_RELEASE_SCALES  = 2,
    TQ_ABI_RELEASE_ZEROS   = 3
} tq_abi_release_kind;

/* ---- ABI entry points ---- */

/* Encode `n` f32 elements into caller-owned output buffers.
 *
 * On entry, every `out_*` slot must point to caller-owned storage
 * whose capacity is at least the value in `out_*_capacity`. On
 * success the dispatcher writes into those buffers and reports the
 * populated lengths via `tq_abi_encode_result`. On any failure
 * the output slots are reset to NULL and the result status is set
 * to the matching error code; the caller sees a clean state.
 */
tq_abi_encode_result tq_abi_encode(const tq_abi_encode_request* req);

/* Decode into a caller-owned `out_ptr` buffer of length `n`.
 *
 * On any validation failure the caller's `out_ptr` and its contents
 * are guaranteed untouched. On success the buffer is overwritten
 * with the reconstructed f32 values.
 */
tq_abi_status tq_abi_decode(const tq_abi_decode_request* req);

/* Free a heap allocation previously returned by `tq_abi_encode`.
 *
 * `kind` selects the matching layout for the buffer; every allocate
 * has exactly one matching release. NULL pointers are ignored.
 */
void tq_abi_release(tq_abi_release_kind kind, void* ptr, size_t count);

#ifdef __cplusplus
}
#endif
#endif /* TQ_ABI_V1_H */

