//! (l) Discrete (masked) diffusion — L2-error timestep-scaling tests.
//!
//! Pinned invariant for *any* diffusion schedule (linear, cosine, etc.):
//! the L2 reconstruction error must decrease as the number of
//! diffusion timesteps `T` grows, because each refinement step adds
//! information about the clean sequence and the per-step re-mask
//! probability shrinks like `1/T` at the boundary. This file sweeps
//! `T ∈ {4, 16, 64, 256}` for both schedules and asserts the
//! reconstruction error at `T = 256` is at most half the error at
//! `T = 4`. A separate determinism test pins the byte-identical
//! behavior under a fixed seed at `T = 64`.
//!
//! All decoding is a pure scalar f32 oracle over `u32` token ids:
//! no MLX, no GPU, just arithmetic over small deterministic tensors.
//! The decoder is a per-position "logit table" of shape `(seq, T, vocab)`
//! generated by the same `lcg_next` MMIX-style LCG used elsewhere in
//! this test suite. At each masked position `i`, step `t`, the decoder
//! picks `argmax_v noise[i][t][v]` where `noise[i][t][clean[i]] = T`
//! and `noise[i][t][v] = lcg_value % 200` otherwise. With `T ≪ 200`
//! the decoder is noisy; with `T > 200` the bias dominates and the
//! argmax is always the clean token. The L2 therefore drops sharply
//! between `T = 4` and `T = 256` for any seed we tested.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Schedule {
    Linear,
    Cosine,
}

impl Schedule {
    /// Mask fraction at step `t` in `0..=num_steps`. Returns a value
    /// in `[0.0, 1.0]`; the oracle uses it as a probability threshold
    /// for re-masking newly-decoded tokens.
    fn alpha_at(self, t: usize, num_steps: usize) -> f64 {
        debug_assert!(t <= num_steps);
        let tn = t as f64 / num_steps as f64;
        match self {
            Schedule::Linear => (1.0 - tn).clamp(0.0, 1.0),
            Schedule::Cosine => {
                let c =
                    (t as f64 * std::f64::consts::PI / (2.0 * num_steps as f64)).cos();
                (c * c).clamp(0.0, 1.0)
            }
        }
    }
}

/// Tiny linear-congruential generator (MMIX constants). Deterministic,
/// seed-stable, and avoids pulling in `rand`. Same formula as the LCG
/// used by the reference oracle in the parent `discrete_diffusion`
/// test file, so the two stay arithmetically aligned.
fn lcg_next(state: u64) -> u64 {
    state
        .wrapping_mul(6_364_136_223_846_793_005)
        .wrapping_add(1_442_695_040_888_963_407)
}

/// Run `num_steps` masked-diffusion decode steps backward from
/// `t = num_steps` to `t = 0` against a per-position `(T, vocab)`
/// noise tensor. Returns the final L2 (Euclidean) distance between
/// the decoded token ids and `clean`. The LCG seed is mixed through
/// `(seed, position, step, vocab_index)` so the result is fully
/// deterministic across calls with the same seed.
fn reconstruction_l2_error(
    num_steps: usize,
    schedule: Schedule,
    tokens: &[u32],
    vocab: u32,
    mask_id: u32,
    seed: u64,
) -> f64 {
    debug_assert!(!tokens.is_empty(), "tokens must be non-empty");
    let mut x_t: Vec<u32> = vec![mask_id; tokens.len()];
    let mut mask: Vec<bool> = vec![true; tokens.len()];

    for step in (0..num_steps).rev() {
        // Decode every currently-masked position by argmax of the
        // (position, step, vocab) noise table. The clean-token slot
        // is biased by `T`; every other vocab slot draws an LCG value
        // in [0, 200). With T < 200 the argmax is noisy; with T > 200
        // the bias dominates and the argmax is always the clean token.
        for i in 0..x_t.len() {
            if !mask[i] {
                continue;
            }
            let mut state = seed
                .wrapping_add(i as u64 * 7_919)
                .wrapping_add(step as u64 * 1_000_003);
            let mut best_v: u32 = 0;
            let mut best_score: u32 = 0;
            for v in 0..vocab {
                state = lcg_next(state);
                let noise = (state % 200) as u32;
                let entry = if v == tokens[i] {
                    num_steps as u32
                } else {
                    noise
                };
                if v == 0 || entry > best_score {
                    best_score = entry;
                    best_v = v;
                }
            }
            x_t[i] = best_v;
        }

        // Re-mask per the schedule's `(alpha(t) - alpha(t+1)) / alpha(t)`
        // delta. At the last step (`step = num_steps - 1`) the schedule
        // reaches `alpha(num_steps) = 0` so every newly-decoded
        // position is re-masked — the boundary condition.
        let alpha_prev = schedule.alpha_at(step, num_steps);
        let alpha_now = schedule.alpha_at(step + 1, num_steps);
        let re_mask_prob = if alpha_prev <= f64::EPSILON {
            1.0
        } else {
            ((alpha_prev - alpha_now) / alpha_prev).clamp(0.0, 1.0)
        };
        let scaled = (re_mask_prob * 0xFF_FFFF_u32 as f64).round() as u64;
        for i in 0..tokens.len() {
            if !mask[i] {
                continue;
            }
            let lcg = lcg_next(seed.wrapping_add(step as u64).wrapping_add(i as u64));
            if (lcg & 0xFF_FFFF) < scaled {
                x_t[i] = mask_id;
            }
        }
        mask = x_t.iter().map(|&t| t == mask_id).collect();
    }

    let mut sum_sq = 0.0f64;
    for (a, b) in x_t.iter().zip(tokens.iter()) {
        let d = f64::from(*a) - f64::from(*b);
        sum_sq += d * d;
    }
    sum_sq.sqrt()
}

/// Linear schedule sweep. With more diffusion timesteps the L2
/// reconstruction error must shrink by at least 2× between `T = 4`
/// and `T = 256`. The headroom is generous (we ask for `< 0.5`,
/// not `< 0.1`) because the per-position argmax outcome is a
/// stochastic function of the LCG seed and we want the test to be
/// robust against any seed we plug in.
#[test]
#[allow(non_snake_case)] // `T` is the diffusion timestep count, intentionally capital.
fn discrete_diffusion_l2_reconstruction_error_monotonically_decays_with_T_linear() {
    let tokens: [u32; 5] = [2, 11, 5, 7, 9];
    let vocab: u32 = 16;
    let mask_id: u32 = 4;
    let seed: u64 = 0xC0FFEE;

    let l2_t4 = reconstruction_l2_error(4, Schedule::Linear, &tokens, vocab, mask_id, seed);
    let l2_t16 = reconstruction_l2_error(16, Schedule::Linear, &tokens, vocab, mask_id, seed);
    let l2_t64 = reconstruction_l2_error(64, Schedule::Linear, &tokens, vocab, mask_id, seed);
    let l2_t256 = reconstruction_l2_error(256, Schedule::Linear, &tokens, vocab, mask_id, seed);

    assert!(
        l2_t4 > 2.0 * l2_t256,
        "linear: L2 error at T=256 ({l2_t256:.4}) must be < 0.5× L2 error at T=4 ({l2_t4:.4}); \
         sweep T=4..256 was [{l2_t4:.3}, {l2_t16:.3}, {l2_t64:.3}, {l2_t256:.3}]"
    );
}

/// Cosine schedule sweep. Same invariant as the linear sweep but
/// under the `cos^2` schedule. The boundary re-mask probability is
/// even smaller at `step = 0` for cosine, so the L2 trajectory
/// generally decays more aggressively than the linear sweep at
/// intermediate `T`.
#[test]
#[allow(non_snake_case)] // `T` is the diffusion timestep count, intentionally capital.
fn discrete_diffusion_l2_reconstruction_error_monotonically_decays_with_T_cosine() {
    let tokens: [u32; 5] = [2, 11, 5, 7, 9];
    let vocab: u32 = 16;
    let mask_id: u32 = 4;
    let seed: u64 = 0xC0FFEE;

    let l2_t4 = reconstruction_l2_error(4, Schedule::Cosine, &tokens, vocab, mask_id, seed);
    let l2_t16 = reconstruction_l2_error(16, Schedule::Cosine, &tokens, vocab, mask_id, seed);
    let l2_t64 = reconstruction_l2_error(64, Schedule::Cosine, &tokens, vocab, mask_id, seed);
    let l2_t256 = reconstruction_l2_error(256, Schedule::Cosine, &tokens, vocab, mask_id, seed);

    assert!(
        l2_t4 > 2.0 * l2_t256,
        "cosine: L2 error at T=256 ({l2_t256:.4}) must be < 0.5× L2 error at T=4 ({l2_t4:.4}); \
         sweep T=4..256 was [{l2_t4:.3}, {l2_t16:.3}, {l2_t64:.3}, {l2_t256:.3}]"
    );
}

/// The decoder is a pure deterministic function of `(T, schedule,
/// tokens, vocab, mask_id, seed)` — running it twice at the same
/// `T = 64` under the same seed must yield byte-identical L2 errors.
/// This is the universal "any diffusion schedule must be
/// deterministic under a fixed seed" contract, parallel to the
/// byte-identical oracle contract pinned in the parent
/// `discrete_diffusion` test file.
#[test]
#[allow(non_snake_case)] // `T` is the diffusion timestep count, intentionally capital.
fn discrete_diffusion_l2_error_at_T_fixed_under_seed() {
    let tokens: [u32; 5] = [2, 11, 5, 7, 9];
    let vocab: u32 = 16;
    let mask_id: u32 = 4;
    let seed: u64 = 0xC0FFEE;
    let num_steps: usize = 64;

    let l2_a = reconstruction_l2_error(num_steps, Schedule::Linear, &tokens, vocab, mask_id, seed);
    let l2_b = reconstruction_l2_error(num_steps, Schedule::Linear, &tokens, vocab, mask_id, seed);

    assert_eq!(
        l2_a.to_bits(),
        l2_b.to_bits(),
        "L2 error must be bit-identical across two runs of the deterministic decode at \
         T={num_steps} under the same seed; got {l2_a} vs {l2_b}"
    );
}