//! (l) Discrete (masked) diffusion — L2-error timestep-scaling tests
//! (legacy / linear / cosine half).
//!
//! Pinned invariant for *any* diffusion schedule (linear, cosine, sqrt,
//! sigmoid): the L2 reconstruction error must decrease as the number of
//! diffusion timesteps `T` grows, because each refinement step adds
//! information about the clean sequence and the per-step re-mask
//! probability shrinks like `1/T` at the boundary. This file sweeps
//! `T ∈ DDM_T_SWEEP` (default `[2, 4, 8, 16, 32, 64, 128, 256, 512]`)
//! for the legacy `Linear` and `Cosine` schedules and asserts the
//! reconstruction error at the largest `T` is at most half the error
//! at the smallest `T`. A separate determinism test pins the
//! byte-identical behavior under a fixed seed at `T = 64`, and a
//! clipping-floor test pins `L2 < 1e-9` at the largest `T = 512`
//! where the decoder's bias (clean-token logit = `T`) dominates the
//! noise (capped at 200) and the argmax is always the clean token.
//!
//! Turn-11 expansion: the same L2-decay contract is now also pinned
//! for the continuous `Sqrt` and `Sigmoid { k }` schedules that
//! `discrete_diffusion_oracle.rs` introduced. The arithmetic of
//! `Schedule::alpha_at` for the new variants mirrors
//! `ContinuousSchedule::alpha_at` byte-for-byte (including the
//! `t == 0` and `t == num_steps` boundary special-cases the sigmoid
//! variant uses), so the local test surface here stays consistent
//! with the production oracle. The turn-11 surface (Sqrt + Sigmoid
//! L2-decay sweeps, clipping-floor pair extension, byte-identical
//! determinism under Sqrt, and the boundary-guard + midpoint
//! relationship pins) lives in the sibling file
//! `discrete_diffusion_l2_continuous.rs`; this file keeps the four
//! legacy tests and the shared helpers (`Schedule`, `lcg_next`,
//! `reconstruction_l2_error`, `DDM_T_SWEEP`, `sweep_t_values`).
//!
//! All decoding is a pure scalar f32 oracle over `u32` token ids:
//! no MLX, no GPU, just arithmetic over small deterministic tensors.
//! The decoder is a per-position "logit table" of shape `(seq, T, vocab)`
//! generated by the same `lcg_next` MMIX-style LCG used elsewhere in
//! this test suite. At each masked position `i`, step `t`, the decoder
//! picks `argmax_v noise[i][t][v]` where `noise[i][t][clean[i]] = T`
//! and `noise[i][t][v] = lcg_value % 200` otherwise. With `T ≪ 200`
//! the decoder is noisy; with `T > 200` the bias dominates and the
//! argmax is always the clean token. The L2 therefore drops sharply
//! between small `T` and `T > 200` for any seed we tested.
//!
//! ## Sweep generality
//!
//! The sweep is parameterised by [`DDM_T_SWEEP`]; the helper
//! [`sweep_t_values`] returns the same slice as a `Vec<usize>` so a
//! future test can layer additional assertions on top of the sweep
//! without re-deriving the constant. The threshold-based check
//! (`L2(T_max) < 0.5 × L2(T_min)`) is intentionally loose because the
//! per-position argmax outcome is a stochastic function of the LCG
//! seed and individual schedules can exhibit non-monotonic dips at
//! intermediate `T` (notably the linear schedule at `T = 64`, where
//! the per-step re-mask probability under `(1 − t/T)` lands close
//! to a local-maximum-noise point).

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Schedule {
    Linear,
    Cosine,
    /// Sqrt mask-fraction `alpha(t) = sqrt(1 - t / num_steps)`.
    /// Slower-than-linear decay: at the mid-step alpha is
    /// `sqrt(1/2) ~= 0.707`, not `0.5`. Used by SEDD-style absorption
    /// schedules. Mirrors `ContinuousScheduleKind::Sqrt` from the
    /// oracle file byte-for-byte.
    Sqrt,
    /// Sigmoid mask-fraction `alpha(t) = 1 / (1 + exp(k * (2*t/N - 1)))`,
    /// centred at `t = N/2` with steepness `k`. Larger `k` yields a
    /// sharper transition through the middle and gentler tails near
    /// the boundaries. Used by MDLM-style reparameterised schedules.
    /// Mirrors `ContinuousScheduleKind::Sigmoid { k }` from the oracle
    /// file byte-for-byte, including the `t == 0` and `t == num_steps`
    /// boundary special-cases that force alpha exactly to 1.0 / 0.0.
    Sigmoid {
        k: i32,
    },
}

impl Schedule {
    /// Mask fraction at step `t` in `0..=num_steps`. Returns a value
    /// in `[0.0, 1.0]`; the oracle uses it as a probability threshold
    /// for re-masking newly-decoded tokens. The boundary invariant
    /// (`alpha(0) == 1.0`, `alpha(num_steps) == 0.0`) is identical to
    /// the production `ContinuousSchedule::alpha_at` in
    /// `discrete_diffusion_oracle.rs`; the local test surface here
    /// exists so the L2-decay tests do not depend on the production
    /// oracle types.
    pub(crate) fn alpha_at(self, t: usize, num_steps: usize) -> f64 {
        debug_assert!(t <= num_steps);
        let tn = t as f64 / num_steps as f64;
        match self {
            Schedule::Linear => (1.0 - tn).clamp(0.0, 1.0),
            Schedule::Cosine => {
                let c = (t as f64 * std::f64::consts::PI / (2.0 * num_steps as f64)).cos();
                (c * c).clamp(0.0, 1.0)
            }
            Schedule::Sqrt => (1.0 - tn).max(0.0).sqrt(),
            Schedule::Sigmoid { k } => {
                // Boundary special-case mirrors the oracle: force
                // alpha exactly to 1.0 / 0.0 at the endpoints so the
                // shared boundary invariant holds regardless of
                // floating-point rounding in the sigmoid body.
                if t == 0 {
                    return 1.0;
                }
                if t == num_steps {
                    return 0.0;
                }
                let kf = k as f64;
                let z = kf * (2.0 * tn - 1.0);
                1.0 / (1.0 + z.exp())
            }
        }
    }
}

/// Programmatic sweep of `T` values used by the L2-decay tests.
///
/// The sweep spans `T = 2` (the smallest non-trivial value where the
/// oracle can do *one* decode pass and a boundary re-mask) up through
/// `T = 512` (the clipping floor where the decoder's bias dominates
/// the noise). Intermediate points double each step so the trajectory
/// is dense at small `T` (where the per-step re-mask probability
/// changes fastest) and coarse at large `T` (where the L2 has already
/// collapsed to the clipping floor). The sweep is exposed as a
/// `&[usize]` so [`sweep_t_values`] can hand a `Vec<usize>` to the
/// caller without copying when ownership isn't needed.
pub(crate) const DDM_T_SWEEP: &[usize] = &[2, 4, 8, 16, 32, 64, 128, 256, 512];

/// Return the canonical `T` sweep as an owned `Vec<usize>`.
///
/// The helper exists so a test can call `sweep_t_values()` and then
/// `.iter()`, `.first()`, `.last()`, `.windows(2)`, etc., without
/// re-declaring the constant in each call site. The returned vector
/// mirrors [`DDM_T_SWEEP`] exactly; the wrapper exists for ergonomic
/// reasons (so callers don't need to import the slice constant
/// directly) and to give future sweeps (e.g. a non-uniform log-spaced
/// variant for SOTA stress coverage) a single insertion point.
pub(crate) fn sweep_t_values() -> Vec<usize> {
    DDM_T_SWEEP.to_vec()
}

/// Tiny linear-congruential generator (MMIX constants). Deterministic,
/// seed-stable, and avoids pulling in `rand`. Same formula as the LCG
/// used by the reference oracle in the parent `discrete_diffusion`
/// test file, so the two stay arithmetically aligned.
pub(crate) fn lcg_next(state: u64) -> u64 {
    state
        .wrapping_mul(6_364_136_223_846_793_005)
        .wrapping_add(1_442_695_040_888_963_407)
}

/// Run `num_steps` masked-diffusion decode steps backward from
/// `t = num_steps` to `t = 0` against a per-position `(T, vocab)`
/// noise tensor. Returns the final L2 (Euclidean) distance between
/// the decoded token ids and `clean`. The LCG seed is mixed through
/// `(seed, position, step, vocab_index)` so the result is fully
/// deterministic across calls with the same seed.
pub(crate) fn reconstruction_l2_error(
    num_steps: usize,
    schedule: Schedule,
    tokens: &[u32],
    vocab: u32,
    mask_id: u32,
    seed: u64,
) -> f64 {
    debug_assert!(!tokens.is_empty(), "tokens must be non-empty");
    let mut x_t: Vec<u32> = vec![mask_id; tokens.len()];
    let mut mask: Vec<bool> = vec![true; tokens.len()];

    for step in (0..num_steps).rev() {
        // Decode every currently-masked position by argmax of the
        // (position, step, vocab) noise table. The clean-token slot
        // is biased by `T`; every other vocab slot draws an LCG value
        // in [0, 200). With T < 200 the argmax is noisy; with T > 200
        // the bias dominates and the argmax is always the clean token.
        for i in 0..x_t.len() {
            if !mask[i] {
                continue;
            }
            let mut state = seed
                .wrapping_add(i as u64 * 7_919)
                .wrapping_add(step as u64 * 1_000_003);
            let mut best_v: u32 = 0;
            let mut best_score: u32 = 0;
            for v in 0..vocab {
                state = lcg_next(state);
                let noise = (state % 200) as u32;
                let entry = if v == tokens[i] {
                    num_steps as u32
                } else {
                    noise
                };
                if v == 0 || entry > best_score {
                    best_score = entry;
                    best_v = v;
                }
            }
            x_t[i] = best_v;
        }

        // Re-mask per the schedule's `(alpha(t) - alpha(t+1)) / alpha(t)`
        // delta. At the last step (`step = num_steps - 1`) the schedule
        // reaches `alpha(num_steps) = 0` so every newly-decoded
        // position is re-masked — the boundary condition.
        let alpha_prev = schedule.alpha_at(step, num_steps);
        let alpha_now = schedule.alpha_at(step + 1, num_steps);
        let re_mask_prob = if alpha_prev <= f64::EPSILON {
            1.0
        } else {
            ((alpha_prev - alpha_now) / alpha_prev).clamp(0.0, 1.0)
        };
        let scaled = (re_mask_prob * 0xFF_FFFF_u32 as f64).round() as u64;
        for i in 0..tokens.len() {
            if !mask[i] {
                continue;
            }
            let lcg = lcg_next(seed.wrapping_add(step as u64).wrapping_add(i as u64));
            if (lcg & 0xFF_FFFF) < scaled {
                x_t[i] = mask_id;
            }
        }
        mask = x_t.iter().map(|&t| t == mask_id).collect();
    }

    let mut sum_sq = 0.0f64;
    for (a, b) in x_t.iter().zip(tokens.iter()) {
        let d = f64::from(*a) - f64::from(*b);
        sum_sq += d * d;
    }
    sum_sq.sqrt()
}

/// Linear schedule sweep. With more diffusion timesteps the L2
/// reconstruction error must shrink by at least 2× between the
/// smallest `T` in [`DDM_T_SWEEP`] and the largest `T`. The headroom
/// is generous (we ask for `< 0.5`, not `< 0.1`) because the
/// per-position argmax outcome is a stochastic function of the LCG
/// seed and the linear schedule in particular can exhibit
/// non-monotonic dips at intermediate `T` (the `(1 − t/T)` re-mask
/// probability lands near 0.5 at `T = 64`, which is a local-maximum
/// of LCG-driven noise). The sweep is iterated programmatically from
/// [`DDM_T_SWEEP`] so coverage can be expanded without test-code
/// edits.
#[test]
#[allow(non_snake_case)] // `T` is the diffusion timestep count, intentionally capital.
fn discrete_diffusion_l2_reconstruction_error_monotonically_decays_with_T_linear() {
    let tokens: [u32; 5] = [2, 11, 5, 7, 9];
    let vocab: u32 = 16;
    let mask_id: u32 = 4;
    let seed: u64 = 0xC0FFEE;

    let sweep = sweep_t_values();
    assert!(
        sweep.len() >= 2,
        "DDM_T_SWEEP must contain at least 2 entries to do an endpoint comparison; got {sweep:?}"
    );
    let t_min = *sweep.first().expect("non-empty sweep");
    let t_max = *sweep.last().expect("non-empty sweep");

    let l2_min: Vec<f64> = sweep
        .iter()
        .map(|&t| reconstruction_l2_error(t, Schedule::Linear, &tokens, vocab, mask_id, seed))
        .collect();
    let l2_t_min = l2_min[0];
    let l2_t_max = *l2_min.last().expect("non-empty L2 vector");

    assert!(
        l2_t_min > 2.0 * l2_t_max,
        "linear: L2 error at T={t_max} ({l2_t_max:.4}) must be < 0.5× L2 error at T={t_min} ({l2_t_min:.4}); \
         sweep T=[{t_min}..{t_max}] yielded L2={:?}",
        l2_min
    );
}

/// Cosine schedule sweep. Same invariant as the linear sweep but
/// under the `cos^2` schedule. The boundary re-mask probability is
/// even smaller at `step = 0` for cosine, so the L2 trajectory
/// generally decays more aggressively than the linear sweep at
/// intermediate `T`. Iterated programmatically from [`DDM_T_SWEEP`].
#[test]
#[allow(non_snake_case)] // `T` is the diffusion timestep count, intentionally capital.
fn discrete_diffusion_l2_reconstruction_error_monotonically_decays_with_T_cosine() {
    let tokens: [u32; 5] = [2, 11, 5, 7, 9];
    let vocab: u32 = 16;
    let mask_id: u32 = 4;
    let seed: u64 = 0xC0FFEE;

    let sweep = sweep_t_values();
    assert!(
        sweep.len() >= 2,
        "DDM_T_SWEEP must contain at least 2 entries to do an endpoint comparison; got {sweep:?}"
    );
    let t_min = *sweep.first().expect("non-empty sweep");
    let t_max = *sweep.last().expect("non-empty sweep");

    let l2_min: Vec<f64> = sweep
        .iter()
        .map(|&t| reconstruction_l2_error(t, Schedule::Cosine, &tokens, vocab, mask_id, seed))
        .collect();
    let l2_t_min = l2_min[0];
    let l2_t_max = *l2_min.last().expect("non-empty L2 vector");

    assert!(
        l2_t_min > 2.0 * l2_t_max,
        "cosine: L2 error at T={t_max} ({l2_t_max:.4}) must be < 0.5× L2 error at T={t_min} ({l2_t_min:.4}); \
         sweep T=[{t_min}..{t_max}] yielded L2={:?}",
        l2_min
    );
}

/// At the largest `T` in the sweep the decoder's per-position bias
/// (`noise[i][t][clean[i]] = T`) strictly dominates the per-vocab
/// noise (`lcg_value % 200`), so the argmax is always the clean
/// token and the L2 reconstruction error collapses to the floating-
/// point floor. This test pins that contract: at the upper end of
/// the sweep the L2 must be indistinguishable from zero. The
/// threshold (`1e-9`) is loose enough to absorb any rounding error
/// in the square-root accumulation (`sum_sq.sqrt()` over five
/// `f64` differences), tight enough that any non-trivial mismatch
/// (even one wrong token out of five) would push the L2 well above
/// `1.0`. The assertion therefore catches both
///
/// 1. a regression that breaks the bias-dominates-noise invariant
///    (e.g. by changing `T` to a smaller value at the largest sweep
///    entry), and
/// 2. a regression that breaks the deterministic-decoder contract
///    (e.g. by introducing a non-deterministic source of logits).
#[test]
#[allow(non_snake_case)] // `T` is the diffusion timestep count, intentionally capital.
fn discrete_diffusion_l2_error_below_clipping_floor_at_T_large() {
    let tokens: [u32; 5] = [2, 11, 5, 7, 9];
    let vocab: u32 = 16;
    let mask_id: u32 = 4;
    let seed: u64 = 0xC0FFEE;

    let sweep = sweep_t_values();
    let t_large = *sweep.last().expect("non-empty sweep");
    assert!(
        t_large > 200,
        "clipping-floor test requires t_large > 200 (the noise cap); got {t_large}"
    );

    // Run both schedules at the upper end of the sweep so a
    // regression in either schedule's clipping-floor behaviour is
    // caught. (At `T > 200` the argmax outcome is identical for
    // both schedules, but the per-step re-mask probability still
    // differs — so we keep both as a defence-in-depth check.)
    let l2_linear =
        reconstruction_l2_error(t_large, Schedule::Linear, &tokens, vocab, mask_id, seed);
    let l2_cosine =
        reconstruction_l2_error(t_large, Schedule::Cosine, &tokens, vocab, mask_id, seed);

    assert!(
        l2_linear < 1e-9,
        "linear: L2 error at T={t_large} ({l2_linear}) must be < 1e-9 (clipping floor); \
         bias=T={t_large} > 200 noise cap, so every argmax should be the clean token"
    );
    assert!(
        l2_cosine < 1e-9,
        "cosine: L2 error at T={t_large} ({l2_cosine}) must be < 1e-9 (clipping floor); \
         bias=T={t_large} > 200 noise cap, so every argmax should be the clean token"
    );
}

/// The decoder is a pure deterministic function of `(T, schedule,
/// tokens, vocab, mask_id, seed)` — running it twice at the same
/// `T = 64` under the same seed must yield byte-identical L2 errors.
/// This is the universal "any diffusion schedule must be
/// deterministic under a fixed seed" contract, parallel to the
/// byte-identical oracle contract pinned in the parent
/// `discrete_diffusion` test file.
#[test]
#[allow(non_snake_case)] // `T` is the diffusion timestep count, intentionally capital.
fn discrete_diffusion_l2_error_at_T_fixed_under_seed() {
    let tokens: [u32; 5] = [2, 11, 5, 7, 9];
    let vocab: u32 = 16;
    let mask_id: u32 = 4;
    let seed: u64 = 0xC0FFEE;
    let num_steps: usize = 64;

    let l2_a = reconstruction_l2_error(num_steps, Schedule::Linear, &tokens, vocab, mask_id, seed);
    let l2_b = reconstruction_l2_error(num_steps, Schedule::Linear, &tokens, vocab, mask_id, seed);

    assert_eq!(
        l2_a.to_bits(),
        l2_b.to_bits(),
        "L2 error must be bit-identical across two runs of the deterministic decode at \
         T={num_steps} under the same seed; got {l2_a} vs {l2_b}"
    );
}
