//! Build script for `native-abi`.
//!
//! Generates `include/abi_v1.h` from the Rust descriptors so polyglot
//! consumers (C, Zig, Mojo, Nim, Go) compile against a header that is
//! guaranteed to match the Rust definitions.
//!
//! Idempotent: writes the file every build; the content is deterministic.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let include_dir = manifest_dir.join("include");
    fs::create_dir_all(&include_dir).expect("create include/");

    // The header content is generated by the library itself via
    // `native_abi::write_c_header()` so the build script only needs to
    // invoke it. We use a tiny inline program here to avoid pulling in
    // `native_abi` as a build dependency.
    //
    // The header source is also embedded into this build script as a
    // constant string; both paths must stay byte-identical.
    let header = build_header();
    let header_path = include_dir.join("abi_v1.h");
    let existing = fs::read_to_string(&header_path).unwrap_or_default();
    if existing != header {
        fs::write(&header_path, &header).expect("write include/abi_v1.h");
        println!("cargo:rerun-if-changed=build.rs");
        println!("cargo:info=wrote {}", header_path.display());
    } else {
        println!("cargo:rerun-if-changed=build.rs");
    }
}

/// Build the v1 C header text.
///
/// Mirrors `native_abi::headers::write_c_header()` byte-for-byte. We keep
/// the two definitions in lock-step by re-emitting the same string here so
/// that `build.rs` doesn't have to depend on the library crate.
fn build_header() -> String {
    use std::fmt::Write as _;
    let mut out = String::with_capacity(4096);
    let _ = writeln!(out, "/* ABI v1 — generated by perf-core/native-abi.");
    let _ = writeln!(
        out,
        " * Do not edit by hand; regenerate from the Rust descriptors."
    );
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "#ifndef TQ_ABI_V1_H");
    let _ = writeln!(out, "#define TQ_ABI_V1_H");
    let _ = writeln!(out, "#include <stdint.h>");
    let _ = writeln!(out, "#include <stddef.h>");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "#ifdef __cplusplus");
    let _ = writeln!(out, "extern \"C\" {{");
    let _ = writeln!(out, "#endif");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Version ---- */");
    let _ = writeln!(out, "#define TQ_ABI_VERSION_MAJOR 1");
    let _ = writeln!(out, "#define TQ_ABI_VERSION_MINOR 0");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "typedef struct tq_abi_version {{");
    let _ = writeln!(out, "    uint16_t major;");
    let _ = writeln!(out, "    uint16_t minor;");
    let _ = writeln!(out, "}} tq_abi_version;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Status codes (stable integer values) ---- */");
    let _ = writeln!(out, "typedef enum tq_abi_status {{");
    let _ = writeln!(out, "    TQ_ABI_OK                  = 0,");
    let _ = writeln!(out, "    TQ_ABI_ERR_NULL_ARG        = 1,");
    let _ = writeln!(out, "    TQ_ABI_ERR_INVALID_BITS    = 2,");
    let _ = writeln!(out, "    TQ_ABI_ERR_INVALID_GROUPSZ = 3,");
    let _ = writeln!(out, "    TQ_ABI_ERR_NONFINITE_INPUT = 4,");
    let _ = writeln!(out, "    TQ_ABI_ERR_OVERFLOW        = 5,");
    let _ = writeln!(out, "    TQ_ABI_ERR_ALLOCATION      = 6,");
    let _ = writeln!(out, "    TQ_ABI_ERR_VERSION_MISMATCH = 7,");
    let _ = writeln!(out, "    TQ_ABI_ERR_BACKEND         = 8");
    let _ = writeln!(out, "}} tq_abi_status;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Encode request ---- */");
    let _ = writeln!(out, "typedef struct tq_abi_encode_request {{");
    let _ = writeln!(out, "    tq_abi_version abi;");
    let _ = writeln!(out, "    const float*    data_ptr;");
    let _ = writeln!(out, "    size_t          n;");
    let _ = writeln!(out, "    uint8_t         bits;");
    let _ = writeln!(out, "    size_t          group_size;");
    let _ = writeln!(out, "    size_t**        out_shape;");
    let _ = writeln!(out, "    size_t          out_shape_capacity;");
    let _ = writeln!(out, "    uint8_t**       out_packed;");
    let _ = writeln!(out, "    size_t          out_packed_capacity;");
    let _ = writeln!(out, "    float**         out_scales;");
    let _ = writeln!(out, "    size_t          out_scales_capacity;");
    let _ = writeln!(out, "    float**         out_zeros;");
    let _ = writeln!(out, "    size_t          out_zeros_capacity;");
    let _ = writeln!(out, "}} tq_abi_encode_request;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Decode request ---- */");
    let _ = writeln!(out, "typedef struct tq_abi_decode_request {{");
    let _ = writeln!(out, "    tq_abi_version abi;");
    let _ = writeln!(out, "    const uint8_t* packed_ptr;");
    let _ = writeln!(out, "    size_t         packed_len;");
    let _ = writeln!(out, "    const float*   scales_ptr;");
    let _ = writeln!(out, "    const float*   zeros_ptr;");
    let _ = writeln!(out, "    size_t         n;");
    let _ = writeln!(out, "    size_t         group_size;");
    let _ = writeln!(out, "    uint8_t        bits;");
    let _ = writeln!(out, "    float*         out_ptr;");
    let _ = writeln!(out, "}} tq_abi_decode_request;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Encode result ---- */");
    let _ = writeln!(out, "typedef struct tq_abi_encode_result {{");
    let _ = writeln!(out, "    int32_t status;");
    let _ = writeln!(out, "    size_t  written_packed_len;");
    let _ = writeln!(out, "    size_t  written_shape_len;");
    let _ = writeln!(out, "    size_t  written_scales_len;");
    let _ = writeln!(out, "    size_t  written_zeros_len;");
    let _ = writeln!(out, "}} tq_abi_encode_result;");
    writeln!(out).expect("write failed");
    let _ = writeln!(
        out,
        "/* ---- Release kinds (matching release per allocation owner) ---- */"
    );
    let _ = writeln!(out, "typedef enum tq_abi_release_kind {{");
    let _ = writeln!(out, "    TQ_ABI_RELEASE_SHAPE   = 0,");
    let _ = writeln!(out, "    TQ_ABI_RELEASE_PACKED  = 1,");
    let _ = writeln!(out, "    TQ_ABI_RELEASE_SCALES  = 2,");
    let _ = writeln!(out, "    TQ_ABI_RELEASE_ZEROS   = 3");
    let _ = writeln!(out, "}} tq_abi_release_kind;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- ABI entry points ---- */");
    writeln!(out).expect("write failed");
    let _ = writeln!(
        out,
        "/* Encode `n` f32 elements into caller-owned output buffers."
    );
    let _ = writeln!(out, " *");
    let _ = writeln!(
        out,
        " * On entry, every `out_*` slot must point to caller-owned storage"
    );
    let _ = writeln!(
        out,
        " * whose capacity is at least the value in `out_*_capacity`. On"
    );
    let _ = writeln!(
        out,
        " * success the dispatcher writes into those buffers and reports the"
    );
    let _ = writeln!(
        out,
        " * populated lengths via `tq_abi_encode_result`. On any failure"
    );
    let _ = writeln!(
        out,
        " * the output slots are reset to NULL and the result status is set"
    );
    let _ = writeln!(
        out,
        " * to the matching error code; the caller sees a clean state."
    );
    let _ = writeln!(out, " */");
    let _ = writeln!(
        out,
        "tq_abi_encode_result tq_abi_encode(const tq_abi_encode_request* req);"
    );
    writeln!(out).expect("write failed");
    let _ = writeln!(
        out,
        "/* Decode into a caller-owned `out_ptr` buffer of length `n`."
    );
    let _ = writeln!(out, " *");
    let _ = writeln!(
        out,
        " * On any validation failure the caller's `out_ptr` and its contents"
    );
    let _ = writeln!(
        out,
        " * are guaranteed untouched. On success the buffer is overwritten"
    );
    let _ = writeln!(out, " * with the reconstructed f32 values.");
    let _ = writeln!(out, " */");
    let _ = writeln!(
        out,
        "tq_abi_status tq_abi_decode(const tq_abi_decode_request* req);"
    );
    writeln!(out).expect("write failed");
    let _ = writeln!(
        out,
        "/* Free a heap allocation previously returned by `tq_abi_encode`."
    );
    let _ = writeln!(out, " *");
    let _ = writeln!(
        out,
        " * `kind` selects the matching layout for the buffer; every allocate"
    );
    let _ = writeln!(
        out,
        " * has exactly one matching release. NULL pointers are ignored."
    );
    let _ = writeln!(out, " */");
    let _ = writeln!(
        out,
        "void tq_abi_release(tq_abi_release_kind kind, void* ptr, size_t count);"
    );
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "#ifdef __cplusplus");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "#endif");
    let _ = writeln!(out, "#endif /* TQ_ABI_V1_H */");
    writeln!(out).expect("write failed");
    out
}
