//! C header generator.
//!
//! The header is the canonical artifact every polyglot consumer (C, Zig,
//! Mojo, Nim, Go) compiles against. The Rust descriptors are the source of
//! truth; this module emits a self-contained `.h` matching them.
//!
//! The header is also written into `perf-core/native-abi/include/abi_v1.h`
//! at build time via `build.rs`. Tests then parse the emitted header to
//! confirm every declared symbol has a matching Rust definition.

/// All symbols the v1 contract requires the C header to declare.
///
/// Anything missing here is a contract violation: polyglot backends
/// (C, Zig, Mojo, Nim, Go) reference these names by string.
pub const HEADER_C_SYMBOLS: &[&str] = &[
    "tq_abi_version",
    "tq_abi_status",
    "tq_abi_encode_request",
    "tq_abi_decode_request",
    "tq_abi_encode_result",
    "tq_abi_encode",
    "tq_abi_decode",
    "tq_abi_release",
    "TQ_ABI_VERSION_MAJOR",
    "TQ_ABI_VERSION_MINOR",
];

/// Emit the canonical C header for ABI v1.
///
/// The output is stable: any change here is a contract change and must be
/// paired with a major-version bump. The header does not depend on any
/// project-local types — only `<stdint.h>` and `<stddef.h>`.
pub fn write_c_header() -> String {
    use core::fmt::Write as _;

    let mut out = String::with_capacity(4096);
    let _ = writeln!(out, "/* ABI v1 — generated by perf-core/native-abi.");
    let _ = writeln!(out, " * Do not edit by hand; regenerate from the Rust descriptors.");
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "#ifndef TQ_ABI_V1_H");
    let _ = writeln!(out, "#define TQ_ABI_V1_H");
    let _ = writeln!(out, "#include <stdint.h>");
    let _ = writeln!(out, "#include <stddef.h>");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "#ifdef __cplusplus");
    let _ = writeln!(out, "extern \"C\" {{");
    let _ = writeln!(out, "#endif");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Version ---- */");
    let _ = writeln!(out, "#define TQ_ABI_VERSION_MAJOR 1");
    let _ = writeln!(out, "#define TQ_ABI_VERSION_MINOR 0");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "typedef struct tq_abi_version {{");
    let _ = writeln!(out, "    uint16_t major;");
    let _ = writeln!(out, "    uint16_t minor;");
    let _ = writeln!(out, "}} tq_abi_version;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Status codes (stable integer values) ---- */");
    let _ = writeln!(out, "typedef enum tq_abi_status {{");
    let _ = writeln!(out, "    TQ_ABI_OK                  = 0,");
    let _ = writeln!(out, "    TQ_ABI_ERR_NULL_ARG        = 1,");
    let _ = writeln!(out, "    TQ_ABI_ERR_INVALID_BITS    = 2,");
    let _ = writeln!(out, "    TQ_ABI_ERR_INVALID_GROUPSZ = 3,");
    let _ = writeln!(out, "    TQ_ABI_ERR_NONFINITE_INPUT = 4,");
    let _ = writeln!(out, "    TQ_ABI_ERR_OVERFLOW        = 5,");
    let _ = writeln!(out, "    TQ_ABI_ERR_ALLOCATION      = 6,");
    let _ = writeln!(out, "    TQ_ABI_ERR_VERSION_MISMATCH = 7,");
    let _ = writeln!(out, "    TQ_ABI_ERR_BACKEND         = 8");
    let _ = writeln!(out, "}} tq_abi_status;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Encode request ---- */");
    let _ = writeln!(out, "typedef struct tq_abi_encode_request {{");
    let _ = writeln!(out, "    tq_abi_version abi;");
    let _ = writeln!(out, "    const float*    data_ptr;");
    let _ = writeln!(out, "    size_t          n;");
    let _ = writeln!(out, "    uint8_t         bits;");
    let _ = writeln!(out, "    size_t          group_size;");
    let _ = writeln!(out, "    size_t**        out_shape;");
    let _ = writeln!(out, "    size_t          out_shape_capacity;");
    let _ = writeln!(out, "    uint8_t**       out_packed;");
    let _ = writeln!(out, "    size_t          out_packed_capacity;");
    let _ = writeln!(out, "    float**         out_scales;");
    let _ = writeln!(out, "    size_t          out_scales_capacity;");
    let _ = writeln!(out, "    float**         out_zeros;");
    let _ = writeln!(out, "    size_t          out_zeros_capacity;");
    let _ = writeln!(out, "}} tq_abi_encode_request;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Decode request ---- */");
    let _ = writeln!(out, "typedef struct tq_abi_decode_request {{");
    let _ = writeln!(out, "    tq_abi_version abi;");
    let _ = writeln!(out, "    const uint8_t* packed_ptr;");
    let _ = writeln!(out, "    size_t         packed_len;");
    let _ = writeln!(out, "    const float*   scales_ptr;");
    let _ = writeln!(out, "    const float*   zeros_ptr;");
    let _ = writeln!(out, "    size_t         n;");
    let _ = writeln!(out, "    size_t         group_size;");
    let _ = writeln!(out, "    uint8_t        bits;");
    let _ = writeln!(out, "    float*         out_ptr;");
    let _ = writeln!(out, "}} tq_abi_decode_request;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Encode result ---- */");
    let _ = writeln!(out, "typedef struct tq_abi_encode_result {{");
    let _ = writeln!(out, "    int32_t status;");
    let _ = writeln!(out, "    size_t  written_packed_len;");
    let _ = writeln!(out, "    size_t  written_shape_len;");
    let _ = writeln!(out, "    size_t  written_scales_len;");
    let _ = writeln!(out, "    size_t  written_zeros_len;");
    let _ = writeln!(out, "}} tq_abi_encode_result;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- Release kinds (matching release per allocation owner) ---- */");
    let _ = writeln!(out, "typedef enum tq_abi_release_kind {{");
    let _ = writeln!(out, "    TQ_ABI_RELEASE_SHAPE   = 0,");
    let _ = writeln!(out, "    TQ_ABI_RELEASE_PACKED  = 1,");
    let _ = writeln!(out, "    TQ_ABI_RELEASE_SCALES  = 2,");
    let _ = writeln!(out, "    TQ_ABI_RELEASE_ZEROS   = 3");
    let _ = writeln!(out, "}} tq_abi_release_kind;");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* ---- ABI entry points ---- */");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* Encode `n` f32 elements into caller-owned output buffers.");
    let _ = writeln!(out, " *");
    let _ = writeln!(out, " * On entry, every `out_*` slot must point to caller-owned storage");
    let _ = writeln!(out, " * whose capacity is at least the value in `out_*_capacity`. On");
    let _ = writeln!(out, " * success the dispatcher writes into those buffers and reports the");
    let _ = writeln!(out, " * populated lengths via `tq_abi_encode_result`. On any failure");
    let _ = writeln!(out, " * the output slots are reset to NULL and the result status is set");
    let _ = writeln!(out, " * to the matching error code; the caller sees a clean state.");
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "tq_abi_encode_result tq_abi_encode(const tq_abi_encode_request* req);");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* Decode into a caller-owned `out_ptr` buffer of length `n`.");
    let _ = writeln!(out, " *");
    let _ = writeln!(out, " * On any validation failure the caller's `out_ptr` and its contents");
    let _ = writeln!(out, " * are guaranteed untouched. On success the buffer is overwritten");
    let _ = writeln!(out, " * with the reconstructed f32 values.");
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "tq_abi_status tq_abi_decode(const tq_abi_decode_request* req);");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "/* Free a heap allocation previously returned by `tq_abi_encode`.");
    let _ = writeln!(out, " *");
    let _ = writeln!(out, " * `kind` selects the matching layout for the buffer; every allocate");
    let _ = writeln!(out, " * has exactly one matching release. NULL pointers are ignored.");
    let _ = writeln!(out, " */");
    let _ = writeln!(out, "void tq_abi_release(tq_abi_release_kind kind, void* ptr, size_t count);");
    writeln!(out).expect("write failed");
    let _ = writeln!(out, "#ifdef __cplusplus");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "#endif");
    let _ = writeln!(out, "#endif /* TQ_ABI_V1_H */");
    writeln!(out).expect("write failed");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_is_well_formed() {
        let h = write_c_header();
        assert!(h.starts_with("/*"));
        assert!(h.contains("#ifndef TQ_ABI_V1_H"));
        assert!(h.contains("#define TQ_ABI_V1_H"));
        assert!(h.contains("#endif /* TQ_ABI_V1_H */"));
    }
}